### ISSUE TITLE
neutron-ha-tool rebalance over all l3-agents

### ISSUE THREAD

**Issue by tpatzig** [sap-oc/crowbar-openstack#25]
During our maintenance in production we had routers distributed like that:

node1: 66
node2: 67
node3: 67
node4: 64
node5: 0

We triggered a `neutron-ha-tool --l3-agent-rebalance` and that results in:

node1: 33
node2: 67
node3: 67
node4: 64
node5: 34

We triggered it again, but the distribution did not change. The assumption was, that neutron-ha-tool would distribute routers over all l3-agent equally and not only from one.

**Comment by matelakat** [comment]
Moving this issue to the corresponding repository , see sap-oc/cookbook-openstack-network#4
