### ISSUE TITLE
Allow adding additional search domains in DNS barclamp

### ISSUE THREAD

**Issue by tpatzig** [sap-oc/crowbar-openstack#28]
Currently only the SOC internal domain is in the domain search list.
We need to add more domains to the nodes search path in resolv.conf

**Comment by vuntz** [comment]
See https://github.com/sap-oc/crowbar-core/pull/9 :-)

**Comment by tpatzig** [comment]
Oh sorry. Then this is already done and we will have that with the next crowbar-core update, right?

**Comment by vuntz** [comment]
> Oh sorry.

Don't be :-)

> Then this is already done and we will have that with the next crowbar-core update, right?

No and yes. Issue is fixed, but that's because github closes issues even when the patch is merged in another org, so right now it's no; but once we'll get our pull request merged, then yes.

**Comment by vuntz** [comment]
https://github.com/sap-oc/crowbar-core/pull/9 was merged
