### ISSUE TITLE
neutron: Use internalURL nova endpoint for notifications

### ISSUE THREAD

**Issue by vuntz** [sap-oc/crowbar-openstack#3]
The Pull request that fixes this issue is here: #10
 - [x] tested
 - [x] reviewed by SUSE
 - [x] reviewed by SAP

Was implemented in https://github.com/crowbar/crowbar-openstack/pull/796

However, the way it's implemented right now will trigger restarts on too many nodes.

**Comment by matelakat** [comment]
needs backport

**Comment by matelakat** [comment]
> needs backport

There was already a PR for this. Now re-triggered the CI to see if it passes.
