### ISSUE TITLE
Ability to change agent_boot_time for neutron

### ISSUE THREAD

**Issue by vuntz** [sap-oc/crowbar-openstack#36]
With one outage, we realized that some flows were missing on nodes due to the fact that the agent_boot_time value is to low.

**Comment by matelakat** [comment]
It's not yet merged to our source, so re-opening it.

**Comment by rsalevsky** [comment]
@matelakat This was the automatic trigger from GitHub. :/

**Comment by matelakat** [comment]
yep, I know.

**Comment by matelakat** [comment]
needs a backport

**Comment by matelakat** [comment]
> needs a backport

already backported, see #37
